#! /bin/ksh
#
#  Initialization script for radiation code
#
RAD_DIR=/scratch/dw569/socrates/trunk
RAD_BIN=${RAD_DIR}/bin
RAD_DATA=${RAD_DIR}/data
RAD_SCRIPT=${RAD_DIR}/sbin
LOCK_FILE="radiation_code.lock"
PATH=$RAD_BIN:$RAD_SCRIPT:$PATH
MANPATH=$RAD_DIR/man:$MANPATH
#
export RAD_DIR
export RAD_BIN
export RAD_DATA 
export RAD_SCRIPT
export LOCK_FILE
export PATH
export MANPATH
#
ulimit -s unlimited
LIBCDF_PATH=/usr/local/netcdf-4.3.3.1/lib
export LD_LIBRARY_PATH=$LIBCDF_PATH:$LD_LIBRARY_PATH
